version: "3.9"

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "078098"
      POSTGRES_DB: "loli"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 4960:5432
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 2s
      timeout: 10s
      retries: 30
      start_period: 10s
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  api:
    image: kingofloli
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/src
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    ports:
      - 5001:5000